In [12]:
#question 1

In [13]:
import numpy as np

In [14]:
def acceptarray(arr):
    print(f"The memory size occupied by the array is {arr.nbytes} bytes")

In [15]:
n1 = np.array([100,34,23,45,78])

In [16]:
acceptarray(n1)

The memory size occupied by the array is 40 bytes


In [17]:
#question 2

In [18]:
n2 = np.array([23,56,21,45,67])

In [19]:
greater = n1>n2

In [20]:
print(greater)

[ True False  True False  True]


In [21]:
greater_equal = n1>=n2

In [22]:
print(greater_equal)

[ True False  True  True  True]


In [23]:
less = n1<n2

In [24]:
print(less)

[False  True False False False]


In [25]:
less_equal = n1<=n2

In [26]:
print(less_equal)

[False  True False  True False]


In [27]:
#question 3

In [29]:
n3 = np.zeros(10)

In [30]:
n4 = np.ones(10)

In [32]:
n5 = np.ones(10)*5

In [33]:
n6 = np.ones(10)*10

In [34]:
n7 = np.ones(10)*20
n8 = np.ones(10)*50

In [35]:
print(n3)
print(n4)
print(n5)
print(n6)
print(n7)
print(n8)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [36]:
#question 4

In [37]:
n9 = np.arange(30,70)

In [38]:
print(n9)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [40]:
#question 5
n10 = np.arange(50,95)
print(n10)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [42]:
#question 6
n11 = np.arange(20,80,2)
print(n11)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [45]:
#question 7
n12 = np.arange(20,80)
for i in n12:
    if (np.mod(i, 2) != 0):#using the numpy mod function
        print(i, end = "  ")

21  23  25  27  29  31  33  35  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71  73  75  77  79  

In [47]:
#question 8 
n13 = np.random.randint(10,40,15)
print(n13)

[30 32 16 29 33 31 17 34 25 38 17 10 29 29 35]


In [48]:
#question 9
n14 = np.random.randint(30,50,10)
print(n14)

[32 45 38 43 45 36 48 30 30 43]


In [49]:
#question 10
n15 = np.random.randint(50,90,20)
print(n15)

[56 82 74 52 84 76 80 58 76 57 62 56 80 78 59 61 58 59 61 71]


In [50]:
#question 11
n16 = np.array([12,34,45,67,89,2])
n17 = np.array([23,45,24,78,67,12])
print(f"The addition of the two arrays is {n16+n17}")
print(f"The division of the two arrays is {n16/n17}")
print(f"The multiplication of the two arrays is {n16*n17}")
print(f"The subtraction of the two arrays is {n16-n17}")


The addition of the two arrays is [ 35  79  69 145 156  14]
The division of the two arrays is [0.52173913 0.75555556 1.875      0.85897436 1.32835821 0.16666667]
The multiplication of the two arrays is [ 276 1530 1080 5226 5963   24]
The subtraction of the two arrays is [-11 -11  21 -11  22 -10]


In [63]:
#question 12
n18= np.arange(10,22).reshape((3, 4))
print(n18)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [64]:
#question 13
n19 = np.eye(3)
print(n19)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [67]:
#question 14
n20 = np.arange(1,10).reshape((3,3))
print(n20)
print(f"The dimentions of the array is {n20.shape}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The dimentions of the array is (3, 3)


In [68]:
#question 15
n21 = np.diag([1,2,3,4,5])#diag function is use to create the this type of the matrix
print(n21)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [71]:
#question 16
n22 = np.random.random((3,3,3))
print(n22)

[[[0.88409177 0.54333032 0.31441054]
  [0.80720469 0.62809975 0.41441466]
  [0.09132087 0.77159434 0.42451141]]

 [[0.93667209 0.34803438 0.11538029]
  [0.63163217 0.79181167 0.60092994]
  [0.34899587 0.54130343 0.19857069]]

 [[0.2138809  0.21062899 0.40707649]
  [0.14778636 0.51255217 0.9833288 ]
  [0.15979867 0.79819875 0.08304544]]]


In [72]:
#question 17
n23 = np.random.random((2,3,4))
print(n23)

[[[0.75643137 0.97802016 0.74226313 0.62482596]
  [0.08035844 0.51625642 0.08004271 0.84343856]
  [0.95471638 0.01717809 0.46397338 0.78778307]]

 [[0.20855186 0.24633704 0.75596422 0.90995842]
  [0.12380752 0.02942846 0.41071575 0.70310469]
  [0.72976663 0.41938804 0.36523505 0.06548267]]]


In [73]:
#question 18
n24 = [23,56,12,78,25]
arr = np.array(n24)
print(arr)

[23 56 12 78 25]


In [76]:
#question 19
n25 = np.arange(2,11).reshape((3,3))
print(n25)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [77]:
#question 20
n26 = np.arange(12,38)
print(n26)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [80]:
#question 21
print(np.flipud(n26))#using the filpud function you can reverse the array

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [81]:
#question 22
print(np.asfarray(n26))

[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.
 30. 31. 32. 33. 34. 35. 36. 37.]


In [82]:
#question 23
n27 = [12,4,5,6,78]
arr = np.array(n27)
print(arr)

[12  4  5  6 78]


In [87]:
#question 24
n28 = [23,45,67,89,8]
arr = np.array(n28)
print(np.remainder(arr,5))

[3 0 2 4 3]


In [89]:
#question 25
n29 = np.arange(20,50)
print(np.remainder(n29,3))

[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
